### ISSUE TITLE
Specification has external spec broken links

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-extensions#33]
Following editorial issues are identified:

Couldn't find "PermissionDescriptor" in this document or other cited documents: [dom], [html], [infra], [mediacapture-streams], [permissions], [webaudio], and [webidl]. See search matches for "PermissionDescriptor" or Learn about this error. Occurred at: 1. (Plugin: "core/xref").
Couldn't find "Initialize the underlying source" in this document or other cited documents: [dom], [html], [infra], [mediacapture-streams], [permissions], [webaudio], and [webidl]. See search matches for "Initialize the underlying source" or Learn about this error. Occurred at: 1. (Plugin: "core/xref").
Couldn't find "tieSourceToContext", for "MediaStreamTrack", in this document or other cited documents: [dom], [html], [infra], [mediacapture-streams], [permissions], [webaudio], and [webidl]. See search matches for "tieSourceToContext" or Learn about this error. Occurred at: 1. (Plugin: "core/xref").
Bad reference: [GETUSERMEDIA] (appears 3 times) (Plugin: "core/render-biblio").
Bad reference: [permissions] (appears 1 times) (Plugin: "core/render-biblio").
Bad reference: [RFC2119] (appears 1 times) (Plugin: "core/render-biblio").
Bad reference: [RFC8174] (appears 1 times) (Plugin: "core/render-biblio").
Bad reference: [HTML] (appears 0 times) (Plugin: "core/render-biblio").
Bad reference: [mediacapture-streams] (appears 0 times) (Plugin: "core/render-biblio").
Bad reference: [infra] (appears 0 times) (Plugin: "core/render-biblio").
Bad reference: [webidl] (appears 0 times) (Plugin: "core/render-biblio").

**Comment by youennf** [comment]
@dontcallmedom any idea on how to fix these?

**Comment by youennf** [comment]
Also we use both GETUSERMEDIA and mediacapture-streams, I guess we should pick one.

**Comment by dontcallmedom** [comment]
The problem with `PermissionDescriptor` and `PermissionName` is a combination of a permission spec bug and a [respec bug](https://github.com/w3c/respec/issues/3764) - hopefully they should go away on their own soon.

"Initialize the underlying source" cannot be referenced because it isn't exported in the getusermedia spec - I'll do a PR there.

I'm not seeing the "bad reference" messages?
