### ISSUE TITLE
Detect OS-level mutation?

### ISSUE THREAD

**Issue by yuhonglin** [w3c/mediacapture-extensions#67]
Hi all,

It seem currently the `mute` event and the `muted` status of `MediaStreamTrack` don't reflect the OS-level settings. For example, if a user mutes the mic in OS setting, there is no way for webapps to get notified about it. How do you think we make OS-level mutation also trigger the "mute" event?

Thanks!

**Comment by youennf** [comment]
> How do you think we make OS-level mutation also trigger the "mute" event?

This is the intent of the spec AFAIUI, though this is a UA choice.
Maybe this is just a limitation of current implementations in which case bug reports on corresponding UA might help?

**Comment by yuhonglin** [comment]
Ah, cool. That is good news. I am actually a chrome/chromeOS developer :) and I think we will be glad to implement it in chromeOS.

**Comment by youennf** [comment]
As a side note, there is also https://bugs.chromium.org/p/chromium/issues/detail?id=1285805 in that area that would be nice to  implement.

**Comment by yuhonglin** [comment]
Cool, thanks! I know little about Android system... but that tracker is indeed a nice reference. Glad to see people like hta@chromium.org agree with the idea.

**Comment by yuhonglin** [comment]
Filed https://crbug.com/1332501. Mark it as Pr-3 because there is still no concrete plan for it.

**Comment by yuhonglin** [comment]
closed this issue and conversation about implementation on cros continues on https://crbug.com/1332501
