### ISSUE TITLE
MediaStreamTrack: actual frame rates captured

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-extensions#76]
Sub-issue of https://github.com/w3c/mediacapture-main/issues/826.

track.getSettings() already gives us the setting (assuming https://github.com/w3c/mediacapture-main/issues/906 is fixed), but it's still useful to know what the actual frame rate is as it could be lower if...
- Camera is unable to produce the FPS of the setting (e.g. poor lighting).
- Frames are produced but dropped (e.g. frame decimation or pipeline not consuming frames fast enough).

Edit: New proposal:
- Just add framesCaptured. The "frames emitted" or similar can be observed from other APIs later in the pipeline.

Previous proposal: track.framesEmitted + track.framesDropped = framesCaptured

**Comment by jan-ivar** [comment]
Don't we [already have this in stats](https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-framespersecond) for peer connection-related use cases? Also [works outside of peer-connection](https://jsfiddle.net/jib1/m4kf5nz3/) in a pinch.

For playback, frame-rates [appear measurable on the video element](https://jsfiddle.net/jib1/yvzmnh05/) in Chrome and Firefox (dunno what Safari has here). What other use cases are there?

**Comment by jan-ivar** [comment]
> track.framesEmitted: Total counter of frames emitted by the source.

This explanation confused me. In the PR it appears to instead be frames emitted by the track to its consumer, not the total frame count of the (camera) source. Which is it?

**Comment by henbos** [comment]
@jan-ivar "media-source" frame rates need to be clarified... historically they are the standardized version of "googFrameRateInput". In contrast to the send FPS or encoder FPS, this is the "input FPS", i.e. the rate of frames being input to WebRTC. So with zero frame drops within WebRTC, the media-source's FPS was the maximum possible FPS you could achieve as the send FPS. But frame drops happening prior to WebRTC is not visible in getStats().

```
Frame producer (e.g. Camera) --> Media Source --> Frame consumer
                              |                |
                              |          framesEmitted
                              |
            framesDropped = delta between framesProduced and framesEmitted (not in getStats)
```

Arguably you could add framesDropped to getStats(), but there are several use cases where we want to know about framesDropped or framesProduced where WebRTC isn't involved. What would be the argument for adding metrics useful outside of WebRTC to WebRTC specific APIs? Why not just add them to the track?

**Comment by henbos** [comment]
Changed this to only include framesCaptured
