### ISSUE TITLE
Clarify which event loop task will be used for track in configuration change .

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-extensions#86]
As originally posted by @youennf in https://github.com/w3c/mediacapture-extensions/pull/83#discussion_r1094215603, it is not very clear whether each clone track will fire in its own event loop task or in the same event loop task when the User Agent detects a change of configuration in a track's underlying source.

**Comment by youennf** [comment]
WebKit is currently queueing a task to fire the event.
This is simpler, the small downsides is that, two cloned tracks may have different capabilities for a small amount of time.

**Comment by jan-ivar** [comment]
It seems common in the platform to queue a task per event fired, with some exceptions, like SRD, which cause a lot of grief to implementers.
