### ISSUE TITLE
mediastream cannot handle webcam data stream in yuv pixel format correctly

### ISSUE THREAD

**Issue by Danjuanlab** [w3c/mediacapture-extensions#99]
Currently using webrtc to open the local webcam device, only when the pixel format of the webcam is srgb or mjpeg, the color rendered to the canvas or video is correct. When the connected webcam is a hardware camera capture card, or an obs virtual camera. Both of these are transmitted in yuv pixel format. When the GPU hardware acceleration of the browser is turned off, the colors rendered to the video and canvas are wrong. When the browser hardware acceleration is turned on, the color rendering in the video tag is correct, but the canvas is still wrong.

Since the mediastream object does not provide restrictions such as pixel format or color space, and so far I have not found any method to directly read the raw data byte stream in the mediaStream, so as a developer, it is impossible to judge whether the webcam opened by the user is What pixel format, and then do subsequent color conversion.

![image](https://github.com/w3c/mediacapture-extensions/assets/42509669/a079618a-adf1-4bca-852e-6020bcf59c34)
![image](https://github.com/w3c/mediacapture-extensions/assets/42509669/450bdbb7-9ac2-409e-83b0-3549a0542857)

![屏幕截图 2022-03-14 112300333](https://github.com/w3c/mediacapture-extensions/assets/42509669/1559c68c-d689-457b-b075-a2cca7e1e904)

**Comment by guidou** [comment]
You can use MediaStreamTrackProcessor to look at the raw data of a track.

**Comment by aboba** [comment]
Closing - this is an implementation issue, not a spec issue. mediacapture-transform MSTP method allows access to VideoFrames, which support color conversion.
